packages:
  - apps/*
  - packages/*
  - e2e

catalog:
  '@formatjs/intl-localematcher': ^0.6.1
  '@hookform/resolvers': ^5.2.1
  '@sentry/nextjs': ^10.3.0
  '@t3-oss/env-core': ^0.13.8
  '@t3-oss/env-nextjs': ^0.13.8
  '@types/negotiator': ^0.6.4
  '@types/node': ^24.2.1
  international-types: ^0.8.1
  lucide-react: ^0.539.0
  negotiator: ^1.0.0
  next: ^15.4.6
  next-international: ^1.3.1
  next-themes: ^0.4.6
  react-hook-form: ^7.62.0
  server-only: ^0.0.1
  svix: ^1.71.0
  typescript: ^5.9.2
  zod: ^4.0.17

catalogs:
  react19:
    '@types/react': ^19.1.9
    '@types/react-dom': ^19.1.7
    react: ^19.1.1
    react-dom: ^19.1.1
  tailwind:
    '@tailwindcss/postcss': ^4.1.11
    '@tailwindcss/typography': ^0.5.16
    postcss: ^8.5.6
    tailwind-merge: ^3.3.1
    tailwindcss: ^4.1.11
    tw-animate-css: ^1.3.6
