packages:
  - "apps/*"
  - "packages/*"
  - "e2e"


catalog:
  "@formatjs/intl-localematcher": "^0.6.1"
  "@hookform/resolvers": "^5.0.1"
  "@t3-oss/env-core": "^0.13.4"
  "@t3-oss/env-nextjs": "^0.13.4"
  "@types/negotiator": "^0.6.3"
  "@types/node": "^22.15.21"
  "international-types": "^0.8.1"
  "lucide-react": "^0.511.0"
  "negotiator": "^1.0.0"
  "next-international": "^1.3.1"
  "next-themes": "^0.4.6"
  "next": "^15.3.2"
  "react-hook-form": "^7.56.4"
  "server-only": "^0.0.1"
  "typescript": "^5.8.3"
  "zod": "^3.25.26"

catalogs:
  tailwind:
    "tailwind-merge": "^3.3.0"
    "tailwindcss": "^4.1.7"
    "@tailwindcss/postcss": "^4.1.7"
    "@tailwindcss/typography": "^0.5.16"
    "tw-animate-css": "^1.3.0"
    "postcss": "^8.5.3"

  react19:
    "react": ^19.1.0
    "react-dom": ^19.1.0
    "@types/react": ^19.1.5
    "@types/react-dom": ^19.1.5