packages:
  - apps/*
  - packages/*
  - e2e

catalog:
  '@formatjs/intl-localematcher': ^0.6.1
  '@hookform/resolvers': ^5.1.1
  '@sentry/nextjs': ^9.32.0
  '@t3-oss/env-core': ^0.13.8
  '@t3-oss/env-nextjs': ^0.13.8
  '@types/negotiator': ^0.6.4
  '@types/node': ^24.0.4
  international-types: ^0.8.1
  lucide-react: ^0.523.0
  negotiator: ^1.0.0
  next-international: ^1.3.1
  next-themes: ^0.4.6
  next: ^15.3.4
  react-hook-form: ^7.58.1
  server-only: ^0.0.1
  svix: ^1.67.0
  typescript: ^5.8.3
  zod: ^3.25.67

catalogs:
  tailwind:
    tailwind-merge: ^3.3.1
    tailwindcss: ^4.1.10
    '@tailwindcss/postcss': ^4.1.10
    '@tailwindcss/typography': ^0.5.16
    tw-animate-css: ^1.3.4
    postcss: ^8.5.6
  react19:
    react: ^19.1.0
    react-dom: ^19.1.0
    '@types/react': ^19.1.8
    '@types/react-dom': ^19.1.6
