services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    ports:
      - "6005:3000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-mypassword}@postgres-umami:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: replace-me-with-a-random-string
    depends_on:
      - postgres-umami
    init: true
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-umami:
    container_name: postgres-umami
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_UMAMI_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_UMAMI_PASSWORD:-mypassword}
      POSTGRES_DB: ${POSTGRES_DB:-umami}
      PGDATA: /data/postgres
    volumes:
       - postgres-umami:/data/postgres
    restart: unless-stopped

  postgres:
    container_name: postgres_forge
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  bugsink:
    image: bugsink/bugsink
    restart: unless-stopped
    environment:
      SECRET_KEY: ${BUG_SINK_SECRET_KEY:-secret_key}
      CREATE_SUPERUSER: ${BUG_SINK_ADMIN:-admin}:${BUG_SINK_ADMIN_PW:-admin}
    ports:
      - "8005:8000"

volumes:
    postgres:
    postgres-umami:
