name: sbrubbles-forge

services:
  umami:
    container_name: umami.sbrubbles
    image: ghcr.io/umami-software/umami:postgresql-latest
    ports:
      - "6005:3000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-mypassword}@postgres_forge:5432/umami_db
      DATABASE_TYPE: postgresql
      APP_SECRET: replace-me-with-a-random-string
    depends_on:
      - postgres_forge
    init: true
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - sbrubbles-forge-network

  postgres_forge:
    container_name: postgres.sbrubbles
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypassword}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}  # Default database, additional ones created by init script
      PGDATA: /data/postgres
    volumes:
       - postgres_forge:/data/postgres
       - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - sbrubbles-forge-network

  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy.sbrubbles
    command:
      - serve
    volumes:
      - ntfy:/var/cache/ntfy
      - ntfy-etc:/etc/ntfy
    ports:
      - 8010:80
    restart: unless-stopped
    networks:
      - sbrubbles-forge-network

volumes:
    ntfy:
    ntfy-etc:
    postgres_forge:

networks:
  sbrubbles-forge-network:
    driver: bridge
    name: sbrubbles-forge-network
