name: Playwright Tests
on:
  push:
  pull_request:



jobs:
  test:
    timeout-minutes: 60
    runs-on: docker
    container:
      image: node:23.7

    services:
      pgsql:
        image: postgres:15
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: postgres

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Prepare repository
        run: git fetch --unshallow --tags

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        working-directory: e2e
        run: npx playwright install --with-deps

      - name: Build
        run: pnpm build

      - name: Run Playwright tests
        working-directory: e2e
        run: npx playwright test

#      - uses: actions/upload-artifact@v3
#        if: ${{ !cancelled() }}
#        with:
#          name: playwright-report
#          path: playwright-report/
#          retention-days: 30
